**<h1>Tarea 5</h1>**

<h3>Solución</h3>

Definimos las funciones que realizan la regresión lineal y cuadrática.

En ambos casos, las funciones reciben los datos en un argumento llamado `datos`, el cual es un arreglo de numpy de $n\times 2$, donde $n$ es el número de puntos. Además, se incluye también un argumento booleano `metrics` que, por defecto (es decir, si no se especifica) toma el valor `False`. Si este argumento es `True`, las funciones imprimen las métricas de rendimiento $S_{y/x}$, $S_r$, etc.

En ambos casos, la función regresa una tupla con los valores de los coeficientes que definen a la recta, o parábola, aproximada.

In [3]:
import numpy as np

def regresion_lineal(datos, metrics=True):
    n = datos.shape[0]
    x_prom = np.mean(datos,axis=0)[0]
    y_prom = np.mean(datos,axis=0)[1]
    sum_xy = np.sum(datos[:,0]*datos[:,1])
    sum_x_2s = np.sum(datos[:,0]*datos[:,0])
    sum_x = np.sum(datos[:,0])
    sum_y = np.sum(datos[:,1])
    a_1 = (n*sum_xy - sum_x*sum_y)/(n*sum_x_2s - sum_x**2)
    a_0 = y_prom - a_1*x_prom
    print(f"Pendiente: {a_1}, Intercepto: {a_0}")
    if metrics:
        S_t = np.sum((datos[:,1]-y_prom)**2)
        S_r = np.sum((datos[:,1]-evaluar_lineal((a_1,a_0),datos[:,0]))**2)
        s_y = np.sqrt(S_t/(n-1))
        s_yx = np.sqrt(S_r/(n-2))
        r2 = (S_t-S_r)/S_t
        print(f"Error respecto al promedio: {S_t}")
        print(f"Error cuadrático: {S_r}")
        print(f"S_r < S_t : {S_r<S_t}")
        print(f"Desviación estandar de los datos y_i: {s_y}")
        print(f"Error estandar de la estimación (s_yx): {s_yx}")
        print(f"S_yx < S_y : {s_yx<s_y}")
        print(f"Coeficiente de determinación r2: {r2}")
    return (a_1,a_0)

In [4]:
import numpy as np

def regresion_cuadratica(datos, metrics=True):
    n = datos.shape[0]
    x_prom = np.mean(datos,axis=0)[0]
    y_prom = np.mean(datos,axis=0)[1]
    sum_xy = np.sum(datos[:,0]*datos[:,1])
    sum_xxy = np.sum(datos[:,0]*datos[:,0]*datos[:,1])
    sum_x_2s = np.sum(datos[:,0]*datos[:,0])
    sum_x_3s = np.sum(datos[:,0]**3)
    sum_x_4s = np.sum(datos[:,0]**4)
    sum_x = np.sum(datos[:,0])
    sum_y = np.sum(datos[:,1])
    matriz = np.array([[n,sum_x,sum_x_2s],[sum_x,sum_x_2s,sum_x_3s],[sum_x_2s,sum_x_3s,sum_x_4s]])
    vector_b = np.array([sum_y,sum_xy,sum_xxy])
    coeficientes = np.linalg.solve(matriz,vector_b)
    print(f"a_2: {coeficientes[2]}, a_1: {coeficientes[2]}, a_0: {coeficientes[0]}")
    if metrics:
        S_t = np.sum((datos[:,1]-y_prom)**2)
        S_r = np.sum((datos[:,1]-evaluar_cuadratica(coeficientes,datos[:,0]))**2)
        s_y = np.sqrt(S_t/(n-1))
        s_yx = np.sqrt(S_r/(n-3))
        r2 = (S_t-S_r)/S_t
        print(f"Error respecto al promedio: {S_t}")
        print(f"Error cuadrático: {S_r}")
        print(f"S_r < S_t : {S_r<S_t}")
        print(f"Desviación estandar de los datos y_i: {s_y}")
        print(f"Error estandar de la estimación (s_yx): {s_yx}")
        print(f"S_yx < S_y : {s_yx<s_y}")
        print(f"Coeficiente de determinación r2: {r2}")
    return tuple(coeficientes)

También necesitaremos algunas funciones auxiliares

In [5]:
def evaluar_lineal(coeficientes,x):
    return coeficientes[0]*x + coeficientes[1]

def evaluar_cuadratica(coeficientes,x):
    return coeficientes[2]*x**2 + coeficientes[1]*x + coeficientes[0]

Ahora implementamos la función que ajusta un polinomio de Lagrange a los datos y evalúa en un nuevo punto. La función recibe los datos como un arreglo de numpy de $n\times 2$, donde $n$ es el número de puntos. Además, se especifica el `grado` del polinomio con el que se realizará la interpolación, este grado $d$ debe ser $d\leq n-1$. Finalmente, se especifica el punto `x` donde realizaremos la evaluación. 

La función regresa el valor de la evaluación.

In [7]:
import numpy as np

def interpolacion_lagrange(datos,grado,x):
    n = grado
    if grado <= datos.shape[0]-1:
        sum = 0
        for i in range(0,n+1):
            sum += L(i,n,x,datos)*datos[i,1]
        return sum
    else:
        print("El grado debe ser menor")

def L(i,n,x,datos):
    prod = 1
    for j in range(n+1):
        if j!=i:
            prod *= (x-datos[j,0])/(datos[i,0]-datos[j,0])
    return prod

# Ejercicio 1

Definimos la matriz de coeficientes y el vector con los lados derechos de cada ecuación.

In [8]:
datos = np.array([[4,1600],[8,1320],[12,1000],[16,890],[20,650],[24,560]],dtype=float)

print(datos)

[[   4. 1600.]
 [   8. 1320.]
 [  12. 1000.]
 [  16.  890.]
 [  20.  650.]
 [  24.  560.]]


## Regresión Lineal

Realizamos la regresión lineal con los datos y obtenemos los coeficientes

In [9]:
coeficientes = regresion_lineal(datos,metrics=True)
print(coeficientes)

Pendiente: -52.285714285714285, Intercepto: 1735.3333333333335
Error respecto al promedio: 790533.3333333334
Error cuadrático: 25070.476190476158
S_r < S_t : True
Desviación estandar de los datos y_i: 397.62629021062816
Error estandar de la estimación (s_yx): 79.16829572258733
S_yx < S_y : True
Coeficiente de determinación r2: 0.9682866298821772
(-52.285714285714285, 1735.3333333333335)


Con los coeficientes, realizamos la aproximación pedida

In [10]:
evaluar_lineal(coeficientes=coeficientes,
               x=15)

951.0476190476193

In [11]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X=datos[:,0].reshape(-1,1),y=datos[:,1])
print(lr.coef_,lr.intercept_)
lr.predict([[15]])

[-52.28571429] 1735.3333333333335


array([951.04761905])

## Regresión Polinomial

In [12]:
coeficientes = regresion_cuadratica(datos,metrics=True)
print(coeficientes)

a_2: 1.417410714285743, a_1: 1.417410714285743, a_0: 1947.0000000000048
Error respecto al promedio: 790533.3333333334
Error cuadrático: 5869.285714285713
S_r < S_t : True
Desviación estandar de los datos y_i: 397.62629021062816
Error estandar de la estimación (s_yx): 44.231533677101574
S_yx < S_y : True
Coeficiente de determinación r2: 0.9925755367081898
(1947.0000000000048, -91.97321428571513, 1.417410714285743)


In [13]:
evaluar_cuadratica(coeficientes=coeficientes,
               x=15)

886.31919642857

## Interpolación de Lagrange

In [14]:
num_puntos = datos.shape[0]

interpolacion_lagrange(datos=datos,
                       grado=num_puntos-1,
                       x=15)

917.696533203125

# Ejercicio 2

Para este ejercicio 2 usamos los mismos pasos del ejercicio 1.

In [15]:
datos = np.array([[0,14.621],[8,11.843],[16,9.870],[24,8.418],[32,7.305],[40,6.413]],dtype=float)

print(datos)

[[ 0.    14.621]
 [ 8.    11.843]
 [16.     9.87 ]
 [24.     8.418]
 [32.     7.305]
 [40.     6.413]]


## Regresión Lineal

In [21]:
coeficientes = regresion_lineal(datos,metrics=True)
print(coeficientes)

Pendiente: -0.2003785714285714, Intercepto: 13.752571428571427
Error respecto al promedio: 47.009358000000006
Error cuadrático: 2.039597485714288
S_r < S_t : True
Desviación estandar de los datos y_i: 3.0662471524650456
Error estandar de la estimación (s_yx): 0.7140723852863742
S_yx < S_y : True
Coeficiente de determinación r2: 0.9566129474536902
(-0.2003785714285714, 13.752571428571427)


In [22]:
evaluar_lineal(coeficientes=coeficientes,
               x=27)

8.34235

## Regresión Polinomial

In [16]:
coeficientes = regresion_cuadratica(datos,metrics=True)
print(coeficientes)

a_2: 0.0035909598214285544, a_1: 0.0035909598214285544, a_0: 14.518642857142856
Error respecto al promedio: 47.009358000000006
Error cuadrático: 0.06772962857142843
S_r < S_t : True
Desviación estandar de los datos y_i: 3.0662471524650456
Error estandar de la estimación (s_yx): 0.15025492623252926
S_yx < S_y : True
Coeficiente de determinación r2: 0.9985592309392647
(14.518642857142856, -0.34401696428571366, 0.0035909598214285544)


In [18]:
evaluar_cuadratica(coeficientes=coeficientes,
               x=27)

7.847994531250003

## Intepolación usando Polinomios de Lagrange

In [19]:
num_puntos = datos.shape[0]

interpolacion_lagrange(datos=datos,
                       grado=num_puntos-1,
                       x=27)

7.968238960266113

## Conclusiones

En este caso, quien quedó más cerca del valor exacto fue la interpolación con polinomios de Lagrange