<a href="https://colab.research.google.com/github/gmauricio-toledo/MetodosNumericos/blob/main/Tarea4_SOL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<h1>Tarea 4</h1>**

<h3>Solución</h3>

Definimos la función que realiza la eliminación Gaussiana. Esta función recibe una matriz aumentada de tamaño $n× (n+1)$.

La función también recibe un argumento booleano `resultados_parciales`, el cual por defecto (es decir, si no se especifica) toma el valor `False`. Si este argumento es `True`, la función va imprimiendo los pasos intermedios en el procedimiento de la triangularización superior.

In [ ]:
import numpy as np

def eliminacion_gaussiana(A,resultados_parciales=False):
    if resultados_parciales: print("Inicial:\n", A)
    n = A.shape[0]
    for k in range(n-1):
        for i in range(k+1,n):
            ratio = A[i,k]/A[k,k]
            A[i] = A[i]-ratio*A[k]
            if resultados_parciales: print(A)
    if resultados_parciales: print("Forward elimination:\n",A)
    #--- SUSTITUCIÓN HACIA ATRÁS ---
    variables = A[:,n]
    for k in reversed(range(n)):
        for j in range(k+1,n):
            variables[k] = variables[k] - A[k,j]*variables[j]
        variables[k] = variables[k]/A[k,k]
    print("Valor de las variables:\n",variables) # Imprimimos las variables
    return variables

# Ejercicio 1

Definimos la matriz de coeficientes y el vector con los lados derechos de cada ecuación.

In [ ]:
A1 = np.array([[3,2,-2,5],[1,-1,3,4],[2,3,1,-1],[1,-3,4,1]],dtype=float)
b1 = np.array([5,-3,-2,4],dtype=float)

print(A1)
print(b1)

[[ 3.  2. -2.  5.]
 [ 1. -1.  3.  4.]
 [ 2.  3.  1. -1.]
 [ 1. -3.  4.  1.]]
[ 5. -3. -2.  4.]


Juntamos la matriz $A$ y el vector $b$ en una sola matriz aumentada, para esto usamos el método [hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html) de numpy.

In [ ]:
matriz_aumentada_1 = np.hstack((A1,b1.reshape(-1,1)))
print(matriz_aumentada_1)

[[ 3.  2. -2.  5.  5.]
 [ 1. -1.  3.  4. -3.]
 [ 2.  3.  1. -1. -2.]
 [ 1. -3.  4.  1.  4.]]


Calculamos la solución del sistema usando la función que realiza la eliminación Gaussiana.

In [ ]:
solucion = eliminacion_gaussiana(matriz_aumentada_1)

Valor de las variables:
 [ 4. -3. -2. -1.]


# Ejercicio 2

Para este ejercicio 2 usamos los mismos pasos del ejercicio 1.

In [ ]:
A2 = np.array([[3,2,1,-3,5],[1,4,2,3,0],[-1,0,4,-1,1],[2,-2,1,-1,0],[3,1,1,7,-5]],dtype=float)
b2 = np.array([23,27,12,-3,11],dtype=float)

print(A2)
print(b2)

[[ 3.  2.  1. -3.  5.]
 [ 1.  4.  2.  3.  0.]
 [-1.  0.  4. -1.  1.]
 [ 2. -2.  1. -1.  0.]
 [ 3.  1.  1.  7. -5.]]
[23. 27. 12. -3. 11.]


In [ ]:
matriz_aumentada_2 = np.hstack((A2,b2.reshape(-1,1)))
print(f"Matriz aumentada del sistema:\n{matriz_aumentada_2}")

Matriz aumentada del sistema:
[[ 3.  2.  1. -3.  5. 23.]
 [ 1.  4.  2.  3.  0. 27.]
 [-1.  0.  4. -1.  1. 12.]
 [ 2. -2.  1. -1.  0. -3.]
 [ 3.  1.  1.  7. -5. 11.]]


In [ ]:
solucion = eliminacion_gaussiana(matriz_aumentada_2)

Valor de las variables:
 [1. 2. 3. 4. 5.]


# Ejercicio 3

Ahora comprobamos nuestras soluciones con las soluciones proporcionadas por el método [solve](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) de numpy.

Ejercicio 1:

In [ ]:
x = np.linalg.solve(A1,b1)

print(f"Solución:\n{x}")

Solución:
[ 4. -3. -2. -1.]


Ejercicio 2:

In [ ]:
x = np.linalg.solve(A2,b2)

print(f"Solución:\n{x}")

Solución:
[1. 2. 3. 4. 5.]
